// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAddLY9TxsTko7HQllB8IhEuBrLs7flLLk',
    appId: '1:718740156599:web:8f5747adcfeb5b1fba9d32',
    messagingSenderId: '718740156599',
    projectId: 'quizflutter-e26e3',
    authDomain: 'quizflutter-e26e3.firebaseapp.com',
    storageBucket: 'quizflutter-e26e3.appspot.com',
    measurementId: 'G-W8TN1PLPL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Oyg_Gv0wSm_48CRcUw_Y84wGPVnQt2Q',
    appId: '1:718740156599:android:ef8f8f877e7c459cba9d32',
    messagingSenderId: '718740156599',
    projectId: 'quizflutter-e26e3',
    storageBucket: 'quizflutter-e26e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiLNmLihCOSOPpzQ4zSXFZofDscQKM0RU',
    appId: '1:718740156599:ios:ce05db486a5b7b30ba9d32',
    messagingSenderId: '718740156599',
    projectId: 'quizflutter-e26e3',
    storageBucket: 'quizflutter-e26e3.appspot.com',
    iosClientId: '718740156599-oss5ab4nrs9f3dicsa5url141nmkf6da.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiLNmLihCOSOPpzQ4zSXFZofDscQKM0RU',
    appId: '1:718740156599:ios:ce05db486a5b7b30ba9d32',
    messagingSenderId: '718740156599',
    projectId: 'quizflutter-e26e3',
    storageBucket: 'quizflutter-e26e3.appspot.com',
    iosClientId: '718740156599-oss5ab4nrs9f3dicsa5url141nmkf6da.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizFlutter',
  );
}
